#!/usr/bin/env bash

mapfile -t monitors < <(evil_get_monitors)

cat "$XDG_CONFIG_HOME/evil_i3wm/eww/widgets.yuck"
printf "\n\n"

for monitor in $(echo "${monitors[*]}")
do
    marr=($(echo $monitor | awk '{str=$1; gsub("::", " ", str); print str}'))
    #########################################################################
    ############################### TOPBAR ##################################
    ######### BAR ELEMENTS

    printf "(defwindow top_bar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"toolbar\"\n"
    printf "                  :geometry (geometry :x \"0%%\"\n"
    printf "                                      :y \"5px\"\n"
    printf "                                      :width \"99%%\"\n"
    printf "                                      :height \"20px\"\n"
    printf "                                      :anchor \"top center\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore false\n"
    printf "  (top_bar :screen %s)\n" ${marr[0]}
    printf ")\n\n"

    ######### POPUPS

    printf "(defwindow pop_calendar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dialog\"\n"
    printf "                  :geometry (geometry :x \"0%%\"\n"
    printf "                                      :y \"60px\"\n"
    printf "                                      :width \"300px\"\n"
    printf "                                      :height \"200px\"\n"
    printf "                                      :anchor \"top center\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_calendar)\n"
    printf ")\n\n"

    printf "(defwindow pop_audio_sinks_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dialog\"\n"
    printf "                  :geometry (geometry :x \"-12%%\"\n"
    printf "                                      :y \"60px\"\n"
    printf "                                      :width \"200px\"\n"
    printf "                                      :height \"150px\"\n"
    printf "                                      :anchor \"top right\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_audio_sinks :screen %s)\n" ${marr[0]}
    printf ")\n\n"

    printf "(defwindow pop_audio_sources_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dialog\"\n"
    printf "                  :geometry (geometry :x \"-4%%\"\n"
    printf "                                      :y \"60px\"\n"
    printf "                                      :width \"200px\"\n"
    printf "                                      :height \"150px\"\n"
    printf "                                      :anchor \"top right\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_audio_sources :screen %s)\n" ${marr[0]}
    printf ")\n\n"

    printf "(defwindow pop_sysmenu_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dialog\"\n"
    printf "                  :geometry (geometry :x \"-1.5%%\"\n"
    printf "                                      :y \"60px\"\n"
    printf "                                      :width \"50px\"\n"
    printf "                                      :height \"200px\"\n"
    printf "                                      :anchor \"top right\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_sysmenu)\n"
    printf ")\n\n"

    #########################################################################
    ############################ BOTTOMBAR ##################################
    ######### BAR ELEMENTS

    printf "(defwindow bottom_bar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"toolbar\"\n"
    printf "                  :geometry (geometry :x \"0%%\"\n"
    printf "                                      :y \"-5px\"\n"
    printf "                                      :width \"99%%\"\n"
    printf "                                      :height \"20px\"\n"
    printf "                                      :anchor \"bottom center\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore false\n"
    printf "  (bottom_bar :screen %s)\n" ${marr[0]}
    printf ")\n\n"

    #########################################################################
    ######################## STANDALONE POPUPS ##############################

    printf "(defwindow pop_whichkey_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dialog\"\n"
    printf "                  :geometry (geometry :x \"0%%\"\n"
    printf "                                      :y \"-15px\"\n"
    printf "                                      :width \"40%%\"\n"
    printf "                                      :height \"20px\"\n"
    printf "                                      :anchor \"bottom center\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_whichkey)\n"
    printf ")\n\n"
done
