#!/usr/bin/env bash

i3-msg -t get_workspaces | tr , "\n" | grep -E "\"name\":|\"visible\"" | awk '{str=$0; gsub("\":", "\" ", str); gsub("\"", "", str); print str;}' | perl -pe 's/\n/ / if $. % 2 != 0' | awk '{print $2 " " $4}' | grep true | awk '{print $1}' | grep -E "$1:"
