#!/usr/bin/env bash

mapfile -t monitors < <(evil_get_monitors)

cat "$XDG_CONFIG_HOME/evil_i3wm/eww/widgets.yuck"
printf "\n\n"

for monitor in $(echo "${monitors[*]}")
do
    marr=($(echo $monitor | awk '{str=$1; gsub("::", " ", str); print str}'))
    printf "(defwindow pop_calendar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"popup\"\n"
    printf "                  :geometry (geometry :anchor \"center center\")\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_calendar)\n"
    printf ")\n\n"

    printf "(defwindow pop_audio_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"popup\"\n"
    printf "                  :geometry (geometry :anchor \"center center\")\n"
    printf "                  :wm-ignore true\n"
    printf "  (pop_audio)\n"
    printf ")\n\n"

    printf "(defwindow topbar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                  :windowtype \"dock\"\n"
    printf "                  :geometry (geometry :x \"0%%\"\n"
    printf "                                      :y \"0%%\"\n"
    printf "                                      :width \"90%%\"\n"
    printf "                                      :height \"10px\"\n"
    printf "                                      :anchor \"top center\"\n"
    printf "                            )\n"
    printf "                  :wm-ignore false\n"
    printf "                  :reserve (struts :side \"top\" :distance \"4%%\")\n"
    printf "  (topbar :screen %s)\n" ${marr[0]}
    printf ")\n\n"

    printf "(defwindow bottombar_%s :monitor %s\n" ${marr[0]} ${marr[0]}
    printf "                     :windowtype \"dock\"\n"
    printf "                     :geometry (geometry :x \"0%%\"\n"
    printf "                                         :y \"0%%\"\n"
    printf "                                         :width \"90%%\"\n"
    printf "                                         :height \"10px\"\n"
    printf "                                         :anchor \"bottom center\"\n"
    printf "                               )\n"
    printf "                     :wm-ignore false\n"
    printf "                     :reserve (struts :side \"bottom\" :distance \"4%%\")\n"
    printf "  (bottombar :screen %s)\n" ${marr[0]}
    printf ")\n\n"
done
