#!/usr/bin/env bash

mapfile -t monitors < <(evil_get_monitors)

for monitor in $(echo "${monitors[*]}")
do
    marr=($(echo $monitor | awk '{str=$1; gsub(":", " ", str); print str}'))
    eval "eww open top_bar_${marr[0]}"
    eval "eww open bottom_bar_${marr[0]}"
done
