#!/usr/bin/env bash

pactl get-source-mute @DEFAULT_SOURCE@ | awk '{if($2 == "yes") {print "0"} else {system("pactl get-source-volume @DEFAULT_SOURCE@ | awk \047{vol=$5; gsub(\042%\042, \042\042, vol); print vol}\047")}}' | awk '$1 ~ /^[0123456789]/'
